// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type NewCardRequest = {
  known: boolean
  word_id: number
}

export type NewCardResponce = {
  user_id: number
  word_id: number
  count_of_views: number
  last_view: string
  msg?: string
}

export type RequestInitData = {
  init_data: string
}

export type ResponceToken = {
  access_token: string
  expires_in: number
  user_id: number
}

export type ReviewRequest = {
  passed: boolean
  word_id: number
}

export type ReviewResponse = {
  message: string
}

export type SetSettingsRequest = {
  /**
   * Must be 1, 2, or 3
   */
  spoiler_settings: number
}

export type SettingsResponse = {
  spoiler_settings: number
  user_id: number
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type WordResponse = {
  word_id: number
  word: string
  translation: string
}

export type WordsResponse = {
  words: Array<WordResponse>
}

export type LoginLoginAccessTokenData = {
  requestBody: RequestInitData
}

export type LoginLoginAccessTokenResponse = ResponceToken

export type SettingsGetUserSettingsData = {
  authorization?: string
}

export type SettingsGetUserSettingsResponse = SettingsResponse

export type SettingsSetUserSettingsData = {
  authorization?: string
  requestBody: SetSettingsRequest
}

export type SettingsSetUserSettingsResponse = SettingsResponse

export type UtilsNewCardData = {
  authorization?: string
  requestBody: NewCardRequest
}

export type UtilsNewCardResponse = NewCardResponce

export type UtilsGetNewWordData = {
  authorization?: string
}

export type UtilsGetNewWordResponse = WordsResponse

export type UtilsAddReviewData = {
  authorization?: string
  requestBody: ReviewRequest
}

export type UtilsAddReviewResponse = ReviewResponse

export type UtilsGetReviewWordsData = {
  authorization?: string
}

export type UtilsGetReviewWordsResponse = WordsResponse

export type UtilsGetReviewWordsCountData = {
  authorization?: string
}

export type UtilsGetReviewWordsCountResponse = number

export type WebhookWebhookResponse = unknown

export type WebhookWebhook1Response = unknown
