// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type NewCardRequest = {
  known: boolean
  word_id: number
}

export type NewCardResponce = {
  user_id: number
  word_id: number
  count_of_views: number
  last_view: string
  msg?: string
}

export type RequestInitData = {
  init_data: string
}

export type ResponceToken = {
  access_token: string
  expires_in: number
  user_id: number
}

export type ReviewRequest = {
  passed: boolean
  word_id: number
}

export type ReviewResponse = {
  message: string
}

export type SentenceResponce = {
  id: number
  native_text: string
  cyrilic_text: string
  latin_text: string
}

export type SettingsResponse = {
  spoiler_settings: number
  user_id: number
  alphabet_settings: number
}

export type SettingsUpdateRequest = {
  /**
   * Must be 1, 2, or 3
   */
  spoiler_settings: number
  /**
   * Must be 1, 2, or 3
   */
  alphabet_settings: number
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type WordResponse = {
  word_id: number
  latin_word: string
  cyrillic_word: string
  native_word: string
  legend?: string | null
  sentences?: Array<SentenceResponce> | null
}

export type WordsResponse = {
  words: Array<WordResponse>
}

export type HealthCheckHealthCheckResponse = unknown

export type LoginLoginAccessTokenData = {
  requestBody: RequestInitData
}

export type LoginLoginAccessTokenResponse = ResponceToken

export type SettingsGetUserSettingsResponse = SettingsResponse

export type SettingsSetUserSettingsData = {
  requestBody: SettingsUpdateRequest
}

export type SettingsSetUserSettingsResponse = SettingsResponse

export type UtilsGetNewWordResponse = WordsResponse

export type UtilsNewCardData = {
  requestBody: NewCardRequest
}

export type UtilsNewCardResponse = NewCardResponce

export type UtilsGetReviewWordsResponse = WordsResponse

export type UtilsAddReviewData = {
  requestBody: ReviewRequest
}

export type UtilsAddReviewResponse = ReviewResponse

export type UtilsGetReviewWordsCountResponse = number

export type WebhookWebhookResponse = unknown
