"""add cyrilic field to word model

Revision ID: 2fed67f4ed4e
Revises: bbc8074ccc4c
Create Date: 2025-03-24 15:55:19.039922

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2fed67f4ed4e'
down_revision = 'bbc8074ccc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('cyrillic_word', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'cyrillic_word')
    # ### end Alembic commands ###
