"""change latin word field

Revision ID: 81bc43e9dbd8
Revises: 2fed67f4ed4e
Create Date: 2025-04-08 13:47:10.589171

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '81bc43e9dbd8'
down_revision = '2fed67f4ed4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('alphabet_settings',
                  sa.Integer(), nullable=False, server_default='3'))
    op.alter_column('word', 'foreign_word', new_column_name='latin_word')
    op.drop_index('ix_word_foreign_word', table_name='word')
    op.create_index(op.f('ix_word_latin_word'), 'word',
                    ['latin_word'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('foreign_word', sa.VARCHAR(
        length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_word_latin_word'), table_name='word')
    op.create_index('ix_word_foreign_word', 'word',
                    ['foreign_word'], unique=True)
    op.drop_column('word', 'latin_word')
    op.drop_column('settings', 'alphabet_settings')
    # ### end Alembic commands ###
