"""remake sentence table

Revision ID: 9d9d5f40348d
Revises: bf87fae774fc
Create Date: 2025-04-14 10:32:17.633238

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9d9d5f40348d'
down_revision = 'bf87fae774fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentence', sa.Column('cyrilic_text', sa.Text(), nullable=False))
    op.add_column('sentence', sa.Column('latin_text', sa.Text(), nullable=False))
    op.alter_column('sentence', 'native_text',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index('ix_sentence_native_text', table_name='sentence')
    op.drop_column('sentence', 'foreign_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentence', sa.Column('foreign_text', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index('ix_sentence_native_text', 'sentence', ['native_text'], unique=False)
    op.alter_column('sentence', 'native_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('sentence', 'latin_text')
    op.drop_column('sentence', 'cyrilic_text')
    # ### end Alembic commands ###
