"""add app models

Revision ID: bbc8074ccc4c
Revises: 84eea2ed8e9f
Create Date: 2025-03-03 10:45:45.623575

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bbc8074ccc4c'
down_revision = '84eea2ed8e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
