"""add cyrillic field

Revision ID: bf87fae774fc
Revises: 81bc43e9dbd8
Create Date: 2025-04-08 14:07:36.795225

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bf87fae774fc'
down_revision = '81bc43e9dbd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
