/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as ReviewImport } from './routes/review'
import { Route as NewImport } from './routes/new'
import { Route as MainImport } from './routes/main'
import { Route as AuthImport } from './routes/auth'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ReviewRoute = ReviewImport.update({
  path: '/review',
  getParentRoute: () => rootRoute,
} as any)

const NewRoute = NewImport.update({
  path: '/new',
  getParentRoute: () => rootRoute,
} as any)

const MainRoute = MainImport.update({
  path: '/main',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/main': {
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/new': {
      preLoaderRoute: typeof NewImport
      parentRoute: typeof rootRoute
    }
    '/review': {
      preLoaderRoute: typeof ReviewImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRoute,
  MainRoute,
  NewRoute,
  ReviewRoute,
  SettingsRoute,
])

/* prettier-ignore-end */
