name: Add to Project

on:
  workflow_dispatch:
  pull_request_target:
  issues:
    types:
      - opened
      - reopened

jobs:
  add-to-project:
    name: Add to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/andrewvect/projects/1
          github-token: ${{ secrets.PROJECTS_TOKEN }}
